### ISSUE TITLE
黑蘋果無法關機、睡眠及重啟問題

### ISSUE THREAD

**Issue by stu640978** [n0TzzZ/HackMac-EFI-OpenCore-for-n0T#1]
您好，小弟使用和您同一塊主板，在按照網上的教程使用Opencore安裝黑蘋果後發現無法正常關機、睡眠和重啟，想請教一下您是否有遇到這個問題，如果有又是如何解決的呢？

電腦配置如下：
主板：技嘉b360m gaming hd
CPU：Intel I7 8700
顯卡：華碩 ROG-STRIX-RX570

**Comment by n0TzzZ** [comment]
很抱歉现在才看到，不知道你是否解决了你的问题？
如果没有，我会尽可能帮助你。

**Comment by stu640978** [comment]
感謝回覆，問題已經解決了。

**Comment by li-yechao** [comment]
@stu640978 请教一下怎么解决的

**Comment by stu640978** [comment]
@li-yechao 可能是配置有問題，重新依照opencore官方文檔配置幾次就正常了，不太確定前面為什麼會出現這些問題。
